// ═══════════════════════════════════════════════
// SIGNAL daily-data.js — March 3, 2026
// AUTO-GENERATED by GitHub Action at 07:00 CET
// Only this file changes daily. index.html is static.
// ═══════════════════════════════════════════════

window.SIGNAL_DATA = {

  date: "Tuesday · March 3, 2026",

  alert: {
    type: "critical",
    icon: "⚡",
    title: "U.S.-IRAN CONFLICT DAY 4 — STRAIT OF HORMUZ THREATENED",
    body: "Iran's Revolutionary Guard declared the Strait of Hormuz closed — 20% of global oil supply at risk. Brent crude topped $85/bbl. All U.S. futures sharply lower. Defense stocks are the only green sector pre-market."
  },

  ticker: [
    { label: "S&P 500",   value: "6,782",    dir: "down", arrow: "▼ 1.45%" },
    { label: "NASDAQ",    value: "22,325",   dir: "down", arrow: "▼ 1.86%" },
    { label: "DOW",       value: "48,155",   dir: "down", arrow: "▼ 1.43%" },
    { label: "RHM.DE",    value: "€1,627",   dir: "flat", arrow: "→ flat" },
    { label: "AMD",       value: "$196",     dir: "down", arrow: "▼ 2.1%" },
    { label: "MSFT",      value: "$427",     dir: "down", arrow: "▼ 1.2%" },
    { label: "NVDA",      value: "$191",     dir: "down", arrow: "▼ 1.5%" },
    { label: "EUNL.DE",   value: "€112.18",  dir: "down", arrow: "▼ 0.05%" },
    { label: "4MMR.DE",   value: "€26.97",   dir: "down", arrow: "▼ 0.94%" },
    { label: "BRENT OIL", value: "$85.10",   dir: "up",   arrow: "▲ 8.1%" },
    { label: "GOLD",      value: "$5,270",   dir: "up",   arrow: "▲ 0.9%" },
    { label: "10Y YIELD", value: "4.09%",    dir: "up",   arrow: "▲ +12bps" }
  ],

  market: [
    { label: "S&P 500",       value: "6,782",   change: "▼ 1.45%",  dir: "down" },
    { label: "Nasdaq 100",    value: "22,325",  change: "▼ 1.86%",  dir: "down" },
    { label: "Dow Jones",     value: "48,155",  change: "▼ 1.43%",  dir: "down" },
    { label: "Brent Crude",   value: "$85.10",  change: "▲ 8.1%",   dir: "up"   },
    { label: "Gold",          value: "$5,270",  change: "▲ 0.9%",   dir: "up"   },
    { label: "10Y Treasury",  value: "4.09%",   change: "▲ +12bps", dir: "up"   }
  ],

  marketSummary: "Monday saw a dramatic intraday comeback — the S&P 500 recovered from a 1.2% loss to close essentially flat at 6,881. The historical playbook on geopolitical dips appeared to hold. But Tuesday pre-market has erased those gains entirely as oil prices surged again following Iran's Strait of Hormuz announcement. This introduces serious inflationary risk, complicating the Fed's path to rate cuts. <strong>Defense stocks are the only sector trading green.</strong>",

  stocks: [
    {
      ticker: "RHM.DE",
      name: "Rheinmetall AG · XETRA",
      price: "€1,627",
      change: "→ flat pre-mkt",
      dir: "flat",
      news: "<strong>🔑 Today:</strong> Iran conflict is a direct catalyst — Rheinmetall is Europe's largest defense prime. Institutional buyers are adding on any dip. Upcoming <strong>FY2025 earnings on March 11</strong> are the biggest near-term event. Pre-guided revenue growth 30–35%, margin 18.5–19%. The Arminius Boxer contract (€12.5bn+) booking is expected in Q1 2026.",
      outlook: "16 analyst Buy ratings, 0 Sells. Deutsche Bank target €2,100. Consensus: <strong>€2,127</strong>. German €100bn+ defense fund + NATO 3.5% GDP = structural multi-year tailwind. March 11 is a ±10% event.",
      badge: "⬆ Strong Buy — Long Term",
      badgeClass: "badge-buy"
    },
    {
      ticker: "NVDA",
      name: "NVIDIA Corporation · NASDAQ",
      price: "~$191",
      change: "▼ 5% post-earnings",
      dir: "down",
      news: "<strong>🔑 Today:</strong> Despite reporting record Q4 FY2026 results last week (revenue $68.1bn, up 73% YoY, EPS $1.62 vs $1.53 expected), NVDA is down on profit-taking and broad market pressure. Q1 FY2027 guidance of <strong>$78bn</strong> crushed estimates of ~$66bn. First Vera Rubin GPU samples shipped to customers last week. Jensen Huang fireside chat today at Morgan Stanley.",
      outlook: "38 analysts rate Strong Buy. Consensus 12-month target: <strong>$263</strong>. At ~25x fwd earnings with 65%+ revenue growth. $500bn Blackwell+Rubin pipeline. $58.5bn remaining in buyback. Buy any dip below $190.",
      badge: "⬆ Strong Buy — AI Kingpin",
      badgeClass: "badge-buy"
    },
    {
      ticker: "AMD",
      name: "Advanced Micro Devices · NASDAQ",
      price: "~$196",
      change: "▼ 2.1% pre-mkt",
      dir: "down",
      news: "<strong>🔑 Today:</strong> AMD presented at Mobile World Congress yesterday — Ryzen AI 400 Series with 60 TOPS NPU targeting AI PCs with HP, Dell, Lenovo in Q2. Today AMD CTO presents at Morgan Stanley TMT Conference — watch for MI450 GPU timeline updates. The Meta 6GW + OpenAI 6GW GPU deals represent the largest non-NVIDIA AI compute commitments ever made.",
      outlook: "H2 2026 story — MI450 shipments start H2. Accumulate below $200. Consensus target <strong>$261</strong>. Microsoft building CUDA-to-AMD translation toolkits. Long runway but patience required.",
      badge: "👁 Buy on Dips — H2 Story",
      badgeClass: "badge-watch"
    },
    {
      ticker: "MSFT",
      name: "Microsoft Corporation · NASDAQ",
      price: "~$427",
      change: "▼ 22% from ATH",
      dir: "down",
      news: "<strong>🔑 Today:</strong> Microsoft is down broadly with tech. The stock has not recovered since the Jan 28 earnings selloff despite strong fundamentals (Azure $50bn+, EPS +24%). Today's Iran escalation adds inflationary pressure which delays rate cuts — a headwind for high-multiple tech. Watch for any Azure deal announcements from the Morgan Stanley TMT conference.",
      outlook: "At ~29x fwd earnings — rare quality at discount. $625bn commercial backlog. Vanguard owns 705M shares (71% institutional). ATH $555 vs current $427 = significant recovery potential. Patient entry.",
      badge: "⬆ Buy the Dip — Quality",
      badgeClass: "badge-buy"
    }
  ],

  etfs: [
    {
      ticker: "EUNL.DE",
      name: "iShares Core MSCI World UCITS ETF",
      stats: "Price: €112.18\nChange: ▼ 0.05%\nCurrency: EUR (Acc.)\nTER: ~0.20% p.a.\nTop: Apple · MSFT · NVDA\nExchange: XETRA",
      badge: "⚖ Core DCA Hold",
      badgeClass: "badge-hold",
      desc: "<strong>Today:</strong> EUNL is being dragged lower by its dominant U.S. tech holdings. The Iran conflict creates a 1.5–2% headwind in U.S. markets which flows directly into EUNL. Partial offsets come from embedded energy and European defense weight.<br><br>EUNL holds NVDA, MSFT, AMD as top positions — so today's AI infrastructure story is already inside your EUNL exposure.",
      verdict: "Core portfolio backbone. Monthly DCA regardless of noise. Use any 5%+ dip as accumulation window. 4th consecutive S&P rally year expected. Historical data: markets are positive 3 months after any geopolitical event."
    },
    {
      ticker: "4MMR.DE",
      name: "Global X Defence Tech UCITS ETF",
      stats: "Price: €26.97\nChange: ▼ 0.94%\n52W: €16.28–€30.18\nAUM: €586m\nTER: 0.50% p.a.\nExchange: XETRA",
      badge: "⬆ Strong Buy — Thematic",
      badgeClass: "badge-buy",
      desc: "<strong>Today:</strong> 4MMR is the direct beneficiary of the Iran conflict — its entire portfolio of defense primes (Rheinmetall, Lockheed, RTX, L3Harris, Northrop, BAE, Leonardo) is in demand. +57.07% in 12 months makes it one of the best-performing ETFs globally. YTD: +8.92%. Best month: Jan 2026 (+13.4%). Doubles in ~1.5 years at current rate.<br><br>At 0.50% TER — reasonable for a pure-play thematic ETF with this performance.",
      verdict: "NATO 5% GDP commitment + EU €800bn defense package + active conflicts = structural multi-year tailwind. Today's Iran news is a fresh catalyst. <strong>Accumulate on dips. Pair with ITA for full transatlantic defense coverage.</strong>"
    },
    {
      ticker: "ITA",
      name: "iShares U.S. Aerospace & Defense ETF",
      stats: "Price: ~$250\nChange: ▲ +2.81% Mon\nAUM: $13.26 billion\n10Y Ann. Return: 17.4%\nTop: RTX · Boeing · GE Aero",
      badge: "⬆ Buy — Iran Catalyst",
      badgeClass: "badge-buy",
      desc: "<strong>Monday:</strong> ITA surged +2.81% while the S&P 500 was down — Lockheed +6%, Northrop +5%, AeroVironment +10%. This is the direct Iran conflict play. Congress approved $900.6bn in defense spending for 2026 — one of the largest budgets in U.S. history. All flows to ITA holdings.<br><br>10-year annualized return of 17.4% makes ITA one of the best long-run ETFs on any exchange.",
      verdict: "The safest large-cap U.S. defense vehicle. Combine <strong>4MMR.DE + ITA</strong> for complete global defense coverage: European tech primes + U.S. mega-caps. Both are strong buys for 2026."
    }
  ],

  macro: [
    { theme: "🛢️ Oil Shock", what: "Iran closed Strait of Hormuz. Brent $85, WTI $77+. Potential $100/bbl if tensions last weeks. Qatar LNG plant shut. 20% of global oil supply at risk.", impact: "💚 Energy (XOM +5%, CVX +4%), Defense, Gold. 🔴 Tech, Airlines (AAL -4%), Cruise (RCL -3%). Fed rate cuts now more distant." },
    { theme: "🤖 AI Capex", what: "Hyperscalers plan ~$700bn AI capex in 2026. NVDA has $500bn in Blackwell+Rubin pipeline. AMD secured 12GW GPU commitments from Meta + OpenAI.", impact: "💚 NVDA, AMD (H2), MSFT long-term. Short-term concern: margins compressed by capex before revenue converts. Best entry windows forming now." },
    { theme: "🏦 Federal Reserve", what: "CME FedWatch: <5% probability of March cut. Oil-driven inflation pushes 10Y yields to 4.09%. Trump openly pushing for lower rates.", impact: "Higher yields pressure tech valuations. 🔴 Growth stocks near-term. 💚 Banks, Financials. Watch today's Fed speeches closely." },
    { theme: "🇩🇪 Germany Rearmament", what: "Germany expects €67bn in defense orders over next 4 quarters. Arminius Boxer program: €37bn in 2026 alone. New financial facility unlocked.", impact: "💚 Rheinmetall, 4MMR.DE, Hensoldt. March 11 Rheinmetall earnings = ±10% event. Orders expected throughout H1 2026." },
    { theme: "🌍 Europe vs U.S.", what: "European equities outperforming in early 2026, led by defense and financials. DAX up ~20% YTD. Institutional rotation into European defense accelerating.", impact: "Consider increasing European allocation via 4MMR.DE, RHM.DE, or broad European ETFs. EUNL benefits even if U.S. lags." }
  ],

  calendar: [
    { date: "Tue Mar 3",    event: "Fed Speeches · AMD @ Morgan Stanley TMT · NVDA Jensen Huang Fireside Chat", why: "AMD CTO: watch for MI450 timeline. Jensen at Morgan Stanley — any Rubin detail moves NVDA. Fed inflation commentary will move rates." },
    { date: "Wed Mar 4",    event: "U.S. ISM Services · Oil Inventory Data", why: "Oil inventory critical with Hormuz risk. ISM Services tracks consumer resilience under higher energy prices." },
    { date: "Fri Mar 6",    event: "🔴 U.S. Non-Farm Payrolls", why: "Strong jobs = Fed holds longer = tech pressure. Weak jobs = rate cut hope returns. Binary outcome for markets." },
    { date: "Tue Mar 10",   event: "Rheinmetall 2025 Annual Report Pre-Release", why: "Key read-through for March 11 earnings. Watch 2026 guidance vs €15–16bn target and order intake figures." },
    { date: "🔴 Wed Mar 11", event: "Rheinmetall FY2025 Earnings + Analyst Conference", why: "Biggest near-term catalyst. 2026 guidance, Arminius booking, order intake. Potential ±10% move in RHM + 4MMR.DE." },
    { date: "Mon Mar 16",   event: "NVIDIA GTC Keynote — Jensen Huang", why: "Major AI event. Vera Rubin architecture details, new partnerships, enterprise AI roadmap. Can move NVDA significantly." }
  ],

  quote: {
    text: "We remain in a bull market despite escalating geopolitical tensions. Futures markets overreacted to the Iranian conflict, creating an opportunity to buy the S&P 500 as it neared its 2026 lows.",
    source: "Jeff Kilburg, CEO, KKM Financial · March 2, 2026"
  }

};
